
select * from customer_purchases limit 10;

-- what's the total revenue generated by male VS female customers?
select gender , sum(purchase_amount) as Revenue 
from customer_purchases
group by gender ;


-- Which customers used discounts but still spend  more than average purchase amount?
select customer_id , purchase_amount
from customer_purchases
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer_purchases);


-- Which are the top 5 products having highest average rating?
select item_purchased , round(avg(review_rating),2) as ratings
from customer_purchases
group by item_purchased
order by ratings DESC
limit 5;


-- compare average purchase amounts between standard and express shiping
select shipping_type, round(avg(purchase_amount),2) as amount
from customer_purchases
group by shipping_type
having shipping_type = 'Express' or  shipping_type = 'Standard';


-- Do subscribed customers spend more? compare average spend and total revenue 
-- between subscribed and non-subscribed customers
select subscription_status, count(customer_id) as Total_Customers , 
sum(purchase_amount) as Total_spend, round(avg(purchase_amount),2) as Average_Spend
from customer_purchases
group by subscription_status;


-- which 5 products have highest percentage of purchase with discounts applied?
select item_purchased ,
ROUND(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100 , 2) as Discount_Rate
from customer_purchases
group by item_purchased
order by Discount_Rate desc
limit 5;


--   segment customers into new , returning  and loyal based on their total number of preveous purchases , and show the count of each segment
with customer_type as (
select customer_id , previous_purchases,
case 
	when previous_purchases = 1 then 'New'
   when previous_purchases between 2 and 10 then 'Returning'
   else 'Loyal'
   end as customer_segment
   from customer_purchases
)
select customer_segment , count(*) as 'Number of Customers'
from customer_type
group by customer_segment;



-- what are the top 3 most purchased products within each category?
with item_count as (
select category, item_purchased,
count(customer_id) as Total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank 
from customer_purchases
group by category, item_purchased
)
select item_rank, category, item_purchased, Total_orders
from item_count
where item_rank <= 3 ;



-- Are customers who  are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, 
count(customer_id) as Repeat_Customers
from customer_purchases
where previous_purchases > 5
group by subscription_status;


-- what's the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as Revenue
from customer_purchases
group by age_group
order by Revenue desc;

